[[service]]
name = "test-stdin"
cmd = "./test-stdin.sh"
cwd = "."
log_capacity = 250
interactive = true

[[service]]
name = "ai-chat"
cmd = "NO_COLOR=1 FORCE_COLOR=0 CI=1 TERM=dumb bunx @builder.io/ai-shell chat"
cwd = "."
log_capacity = 250
interactive = true
pty = true

[[service]]
name = "example-service-1"
cmd = "bun ./index.ts"
cwd = "packages/example-service-1"
log_capacity = 5000

[[service]]
name = "example-service-2"
cmd = "bun ./index.ts"
cwd = "packages/example-service-2"
log_capacity = 5000
